/**********************
*Hello.Java
********************
*Nicholas Chu
*08/19/2020
*CMSC 255
*********************/

public class Hello {

	public static void main(String[] args) {
		System.out.println("<Nicholas Chu>");
		System.out.println("<Hello.Java>");
		System.out.println("<Lab one>");
		System.out.println("<08/19/2020>");
		System.out.println("<CMSC 255>");
		System.out.println();
		}
	}	